// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "ebuy-20200415205005-hostingbucket-ebuyenv",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://ebuy-20200415205005-hostingbucket-ebuyenv.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:2591c771-dad7-4afd-95aa-356b67e569bb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tBs7MQBrI",
    "aws_user_pools_web_client_id": "383g4r8fp9lah65ua4qpa0rpuu",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "products-ebuyenv-ebuyenv",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apid8e90cfc",
            "endpoint": "https://zimdo052e0.execute-api.us-east-1.amazonaws.com/ebuyenv",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
